version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local
    volumes:
      - ./fixtures/mariadb/01_scheme.sql:/docker-entrypoint-initdb.d/01_scheme.sql
      - ./fixtures/02_test_data.sql:/docker-entrypoint-initdb.d/02_test_data.sql
    ports:
      - 3306:3306
