version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local
    volumes:
      - ./fixtures/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
