version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local
    volumes:
      - ./fixtures/scheme.sql:/docker-entrypoint-initdb.d/scheme.sql
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db:
